### ISSUE TITLE
Not working with ember 2.16

### ISSUE THREAD

**Issue by evilcap** [michaljach/ember-cli-deploy-scp#26]
Please, fix it. It is very usefull ember addon

**Comment by michaljach** [comment]
I tested the plugin with 2.16.2 and was successful, could you provide more info ?

**Comment by evilcap** [comment]
I got this error:

`TypeError: chalkColor is not a function
TypeError: chalkColor is not a function
`

**Comment by michaljach** [comment]
Fix was released in https://github.com/michaljach/ember-cli-deploy-scp/pull/28, please check now with a new version of the plugin.
