### ISSUE TITLE
Broken deployment after update to 1.0.10

### ISSUE THREAD

**Issue by roschaefer** [michaljach/ember-cli-deploy-scp#25]
[Our build server couldn't deploy after update to 1.0.10](https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/289983844#L3609)
```
TypeError: chalkColor is not a function
TypeError: chalkColor is not a function
    at Class.log (/home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/ember-cli-deploy-plugin/index.js:92:19)
    at Class.upload (/home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/ember-cli-deploy-scp/index.js:109:16)
    at Object.fn (/home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
    at tryCatch (/home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/travis/build/roschaefer/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
I believe this is an issue of this plugin. I can reproduce it locally.

**Comment by roschaefer** [comment]
Yep, must be this plugin. After reverting the update the deployment succeeds: https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/290005398

**Comment by rennomarcus** [comment]
@roschaefer , you updated the package, but you didn't update your `config/deploy.js`. You should add an array list over there. More info from the [README.md](https://github.com/michaljach/ember-cli-deploy-scp)

**Comment by roschaefer** [comment]
@rennomarcus thanks! That helped. Closing.
